[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 4, y = 8 }
opacity = 1
decorations_theme_variant = "Dark"

[scrolling]
history = 8192

[font]
size = 16
normal = {family = "PlemolJP Console NF", style="Regular"}
offset = {x = 0, y = 0}

[keyboard]
bindings = [
    {key = "C", mods = "Control | Shift", action = "Copy"},
    {key = "V", mods = "Control | Shift", action = "Paste"},
]
